### PR TITLE
Fix a rare crash in TSKSPKIHashCache

### LINKED ISSUE #347: Crash: EXC_BAD_ACCESS KERN_INVALID_ADDRESS in [TSKSPKIHashCache hashSubjectPublicKeyInfoFromCertificate:] line 253
We recently updated our app from TrustKit 3.0.5 to 3.0.6. Now we're seeing EXC_BAD_ACCESS KERN_INVALID_ADDRESS crashes in `[TSKSPKIHashCache hashSubjectPublicKeyInfoFromCertificate:]` line 253. We didn't have any issues with TrustKit before updating.

Could you please look into that? Happy to help, if let me know how. 🙏 

I'll attach the [stacktrace.txt](https://github.com/user-attachments/files/20900069/com.mychime.waveremit_issue_bd6cadc5fa6b580e5efc1fb9c3f9e202_crash_session_6ef33b4f96484ca0b2fd316b3ec7903b_DNE_0_v2_stacktrace.txt).

### PR DESCRIPTION
**Pull request by fabianmuecke**
This PR fixes https://github.com/datatheorem/TrustKit/issues/347 by adding a missing `dispatch_sync` when reading the cache on the main dispatch queue to write it to the file system. This should be safe, as the only `dispatch_barrier_sync` call does not access the main queue, so cannot cause a deadlock.

I tried to find a test that would replicate the issue and found one, that will randomly (maybe once out of 1000 runs) achieve that. All attempts to improve the reliability of the test were futile. I added it the the PR anyway. Feel free to remove, if you think it's useless.

### CODE REVIEW

**Comment by mat1th** [comment]
I do see the same issue in my project. What holds this pr back from merging?

**Review by aztrmobile — APPROVED** [review]

**Comment by NSExceptional** [comment]
Does anyone have a crash log they can share? :)

Edit: oops, from #347:

```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0xafb0 realizeClassWithoutSwift(objc_class*, objc_class*) + 544
1  libobjc.A.dylib                0xacec realizeClassMaybeSwiftMaybeRelock(objc_class*, locker_mixin<lockdebug::lock_mixin<objc_lock_base_t> >&, bool) + 404
2  libobjc.A.dylib                0x9bcc lookUpImpOrForward + 880
3  libobjc.A.dylib                0x4cc4 _objc_msgSend_uncached + 68
4  Foundation                     0x208e8 -[NSDictionary(NSDictionary) encodeWithCoder:] + 484
5  Foundation                     0x21fb8 _encodeObject + 1180
6  Foundation                     0x3bf54 +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 92
7  Sendwave Production            0xcb76d8 __60-[TSKSPKIHashCache hashSubjectPublicKeyInfoFromCertificate:]_block_invoke.17 + 253 (TSKSPKIHashCache.m:253)
...
11 libdispatch.dylib              0x125b0 _dispatch_main_queue_callback_4CF + 44
...
16 UIKitCore                      0x22c62c -[UIApplication _run] + 888
17 UIKitCore                      0x22bc68 UIApplicationMain + 340
18 Sendwave Production            0x8260 main + 14 (main.swift:14)
19 ???                            0x1d59dedcc (Missing)
```

**Comment by ashokds** [comment]
@NSExceptional -- here is another

`TSKSPKIHashCache.m:269
__60-[TSKSPKIHashCache hashSubjectPublicKeyInfoFromCertificate:]_block_invoke.17 + 269`

```
          Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x144c objc_retain_x0 + 16
1  libobjc.A.dylib                0x144c objc_retain + 16
2  Foundation                     0x8ffcf4 -[NSDictionary(NSDictionary) encodeWithCoder:] + 472
3  Foundation                     0x1fd30 _encodeObject + 1176
4  Foundation                     0x94ce04 +[NSKeyedArchiver archivedDataWithRootObject:requiringSecureCoding:error:] + 88
5  DesignIt                     0xf0f704 __60-[TSKSPKIHashCache hashSubjectPublicKeyInfoFromCertificate:]_block_invoke.17 + 269 (TSKSPKIHashCache.m:269)
6  libdispatch.dylib              0x1adc _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x1b7fc _dispatch_client_callout + 16
8  libdispatch.dylib              0x38b10 _dispatch_main_queue_drain.cold.5 + 812
9  libdispatch.dylib              0x10ec8 _dispatch_main_queue_drain + 180
10 libdispatch.dylib              0x10e04 _dispatch_main_queue_callback_4CF + 44
11 CoreFoundation                 0x6a2b4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
12 CoreFoundation                 0x1db3c __CFRunLoopRun + 1944
13 CoreFoundation                 0x1ca6c _CFRunLoopRunSpecificWithOptions + 532
14 GraphicsServices               0x1498 GSEventRunModal + 120
15 UIKitCore                      0x9ddf8 -[UIApplication _run] + 792
16 UIKitCore                      0x46e54 UIApplicationMain + 336
17 DesignIt                     0x650d54 main + 14 (AppDelegate.swift:14)
18 ???                            0x1853c6e28 (Missing)
        
```

**Comment by NSExceptional** [comment]
@fabianmuecke Do you mind if I edit your PR?

**Comment by fabianmuecke** [comment]
> @fabianmuecke Do you mind if I edit your PR?

Not at all. Feel free to do whatever it takes to get a fix merged. 🙂

**Comment by ashok-meena-engcp** [comment]
@NSExceptional @aztrmobile - Please let know when it's expected to get merged. Thanks.

**Comment by NSExceptional** [comment]
@ashok-meena-engcp Sorry for the delay, working on getting this merged ASAP behind the scenes

File: TrustKit/Pinning/TSKSPKIHashCache.m [hunk 1]
```diff
@@ -185,16 +199,21 @@ - (instancetype)initWithIdentifier:(NSString *)uniqueIdentifier
...
+
+- (NSData *)_hashSubjectPublicKeyInfoFromCertificate:(SecCertificateRef)certificate
+{
     // Have we seen this certificate before? Look for the SPKI in the cache
     NSData *certificateData = (__bridge_transfer NSData *)(SecCertificateCopyData(certificate));
-    
-    dispatch_sync(_lockQueue, ^{
-        cachedSubjectPublicKeyInfo = self->_spkiCache[certificateData];
-    });
+    NSData *cachedSubjectPublicKeyInfo = self->_spkiCache[certificateData];
```
Comment (NSExceptional) [inline TrustKit/Pinning/TSKSPKIHashCache.m:236]: `_hashSubjectPublicKeyInfoFromCertificate:` is entirely in the lock queue now

File: TrustKit/Pinning/TSKSPKIHashCache.m [hunk 2]
```diff
@@ -255,35 +274,22 @@ - (NSData *)hashSubjectPublicKeyInfoFromCertificate:(SecCertificateRef)certifica
     
     
     // Store the hash in our memory cache
-    dispatch_barrier_sync(_lockQueue, ^{
-        self->_spkiCache[certificateData] = subjectPublicKeyInfoHash;
-    });
+    self->_spkiCache[certificateData] = subjectPublicKeyInfoHash;
```
Comment (NSExceptional) [inline TrustKit/Pinning/TSKSPKIHashCache.m:297]: `_hashSubjectPublicKeyInfoFromCertificate:` is entirely in the lock queue now

File: TrustKit/Pinning/TSKSPKIHashCache.m [hunk 3]
```diff
@@ -255,35 +274,22 @@ - (NSData *)hashSubjectPublicKeyInfoFromCertificate:(SecCertificateRef)certifica
...
-                TSKLog(@"Protected data not available, skipping SPKI cache persistence");
-            }
-        };
-        
-        if ([NSThread isMainThread]) {
-            updateCacheBlock();
-        }
-        else {
-            dispatch_async(dispatch_get_main_queue(), updateCacheBlock);
+    if (self.spkiCacheFilename.length && isProtectedDataAvailable()) {
```
Comment (NSExceptional) [inline TrustKit/Pinning/TSKSPKIHashCache.m:300]: This _will_ block to call out to the main queue, but that is our last resort, short of refactoring this method and several others to be totally asynchronous, which would be a massive undertaking. The main queue is a well oiled machine and shouldn't be busy for more than a few ms at any given time, and if it is, the app has much bigger problems than blocking this queue waiting on it

**Review by uroboro — APPROVED** [review]

**Review by EthanArbuckle — APPROVED** [review]

**Comment by NSExceptional** [comment]
Thanks for identifying this issue and a fix, @fabianmuecke!

Feel free to open another issue if the crash somehow persists. I did refactor your work quite a bit, but I'm hopeful it still addresses the crash.

**Comment by ashokds** [comment]
> Thanks for identifying this issue and a fix, @fabianmuecke!
> 
> Feel free to open another issue if the crash somehow persists. I did refactor your work quite a bit, but I'm hopeful it still addresses the crash.

Thanks for resolving this @NSExceptional 🎉
